<?php
/**
 * Admin: Book Barcode Labels - พิมพ์ฉลากบาร์โค้ดหนังสือ
 * 
 * ⭐ สำหรับคนมาใหม่:
 * - หน้านี้แสดง barcode labels สำหรับหนังสือทุกเล่ม (ใช้ window.print())
 * - สิทธิ์: staff ขึ้นไป
 * 
 * 📂 Flow:
 * GET → BookRepository::findAllForLabels() → render labels → window.print()
 */

// 🔌 โหลด bootstrap (autoload, config, session, DB)
require_once __DIR__ . '/../bootstrap.php';
// 🔒 [AUTH] staff/admin เท่านั้น — ใช้พิมพ์สติ๊กเกอร์บาร์โค้ดติดหนังสือ
requireStaff();

use App\Repositories\BookRepository;

$bookRepo = new BookRepository(getDB());

// 📚 ดึงหนังสือทั้งหมด (id, title, isbn) สำหรับแสดงในตารางเลือก
$books = $bookRepo->findAllForLabels();

$pageTitle = 'พิมพ์รหัสบาร์โค้ด';
require_once __DIR__ . '/header.php';
?>

<!-- No Print Section -->
<div class="no-print">
    <div class="mb-6 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
            <h3 class="text-2xl font-bold text-gray-800 flex items-center">
                <i class="bi bi-upc-scan mr-3 text-primary-600"></i>
                พิมพ์รหัสบาร์โค้ด (Book Labels)
            </h3>
            <p class="text-gray-500">เลือกหนังสือที่ต้องการพิมพ์สติ๊กเกอร์บาร์โค้ด</p>
        </div>
        <div class="flex gap-2">
            <button onclick="selectAll()" class="px-4 py-2 bg-gray-100 text-gray-700 rounded-xl hover:bg-gray-200 transition-colors text-sm font-medium">
                เลือกทั้งหมด
            </button>
            <button onclick="generateLabels()" class="px-4 py-2 bg-primary-600 text-white rounded-xl hover:bg-primary-700 transition-colors text-sm font-medium shadow-lg shadow-primary-500/30 flex items-center">
                <i class="bi bi-printer-fill mr-2"></i>พิมพ์ที่เลือก
            </button>
        </div>
    </div>

    <!-- Book Selection Table -->
    <div class="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden mb-8">
        <div class="overflow-x-auto max-h-[600px]">
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50 sticky top-0 z-10">
                    <tr>
                        <th class="px-6 py-3 text-left w-10">
                            <input type="checkbox" id="checkAll" onclick="toggleAll(this)" class="rounded border-gray-300 text-primary-600 focus:ring-primary-500 cursor-pointer">
                        </th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ID</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ชื่อหนังสือ</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ISBN</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-32">จำนวน</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    <?php foreach ($books as $book): ?>
                        <tr class="hover:bg-gray-50">
                            <td class="px-6 py-3">
                                <input type="checkbox" name="book_ids[]" value="<?= $book['id'] ?>" data-title="<?= e($book['title']) ?>" data-isbn="<?= e($book['isbn'] ?? $book['id']) ?>"
                                       class="book-checkbox rounded border-gray-300 text-primary-600 focus:ring-primary-500 cursor-pointer">
                            </td>
                            <td class="px-6 py-3 font-mono text-sm text-gray-600"><?= $book['id'] ?></td>
                            <td class="px-6 py-3 font-medium text-gray-900"><?= e($book['title']) ?></td>
                            <td class="px-6 py-3 font-mono text-sm text-gray-500"><?= e($book['isbn'] ?? '-') ?></td>
                            <td class="px-6 py-3">
                                <input type="number" name="qty[<?= $book['id'] ?>]" value="1" min="1" max="100" 
                                       class="w-20 text-center rounded-lg border-gray-300 text-sm focus:ring-primary-500 focus:border-primary-500">
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Print Section (Hidden by default) -->
<div id="printSection" class="hidden print:block">
    <div class="label-grid" id="labelGrid">
        <!-- Labels will be generated by JS -->
    </div>
</div>

<style>
@media print {
    .no-print { display: none !important; }
    #printSection { display: block !important; }
    
    body {
        margin: 0;
        padding: 10mm;
        print-color-adjust: exact;
        -webkit-print-color-adjust: exact;
    }
    
    .label-grid {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 5mm;
    }
    
    .label {
        width: 60mm;
        height: 30mm;
        border: 1px solid #ccc;
        padding: 2mm;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        font-family: 'Sarabun', sans-serif;
        page-break-inside: avoid;
    }
    
    .label .title {
        font-size: 8pt;
        text-align: center;
        margin-bottom: 2mm;
        max-width: 100%;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
    
    .label svg { width: 100% !important; height: 15mm !important; }
    .label .code { font-family: monospace; font-size: 8pt; }
}
</style>

<script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.0/dist/JsBarcode.all.min.js"></script>
<script>
// เลือก/ยกเลิกทั้งหมด — ใช้กับ checkbox “เลือกทั้งหมด” ด้านบน
 function toggleAll(checkbox) {
    document.querySelectorAll('.book-checkbox').forEach(cb => cb.checked = checkbox.checked);
}

function selectAll() {
    document.querySelectorAll('.book-checkbox').forEach(cb => cb.checked = true);
    document.getElementById('checkAll').checked = true;
}

// 🏷️ สร้าง label HTML + barcode แล้วเรียก window.print()
// Flow: เลือกหนังสือ + จำนวน → สร้าง label DOM → JsBarcode render SVG → window.print()
function generateLabels() {
    const selected = document.querySelectorAll('.book-checkbox:checked');
    if (selected.length === 0) {
        modalAlert('กรุณาเลือกหนังสืออย่างน้อย 1 เล่ม', {title: 'แจ้งเตือน', type: 'warning'});
        return;
    }
    
    // 📝 สร้าง label ตามจำนวนที่ระบุ (qty) — แต่ละเล่มอาจพิมพ์หลายใบ
    const grid = document.getElementById('labelGrid');
    grid.innerHTML = '';
    
    selected.forEach(cb => {
        const bookId = cb.value;
        const title = cb.dataset.title || '';
        const isbn = cb.dataset.isbn || bookId; // ใช้ ISBN ถ้ามี, ไม่งั้นใช้ book ID
        const qty = document.querySelector(`input[name="qty[${bookId}]"]`)?.value || 1;
        
        for (let i = 0; i < qty; i++) {
            const label = document.createElement('div');
            label.className = 'label';
            label.innerHTML = `
                <div class="title">${title}</div>
                <svg class="barcode-${bookId}"></svg>
                <div class="code">${isbn}</div>
            `;
            grid.appendChild(label);
        }
    });
    
    // ⏱️ รอ DOM update แล้วค่อย render barcode ผ่าน JsBarcode (CODE128 format)
    setTimeout(() => {
        selected.forEach(cb => {
            const bookId = cb.value;
            const isbn = cb.dataset.isbn || bookId;
            try {
                // 📊 JsBarcode: render SVG barcode ลงใน label
                //    CODE128 รองรับทั้งตัวอักษรและตัวเลข (universal)
                JsBarcode(`.barcode-${bookId}`, isbn, {
                    format: "CODE128",
                    width: 1.5,
                    height: 30,
                    displayValue: false,
                    margin: 0
                });
            } catch (e) {
                console.error('Barcode generation failed for:', isbn, e);
            }
        });
        window.print(); // 🖨️ เปิด print dialog ทันที
    }, 100);
}
</script>

<?php require_once __DIR__ . '/footer.php'; ?>
